version: '2'
services:
  web:
    build: .
    env_file: .env 
    command: mix phoenix.server 
    environment:
      - MIX_ENV=dev 
      - PORT=4000
      - PG_HOST=postgres
      - PG_USERNAME=postgres
    volumes:
      - .:/app 
    ports:
      - "4000:4000"
    links:
      - postgres

  test:
    image: api_web
    env_file: .env
    command: mix test 
    environment:
      - MIX_ENV=test 
      - PORT=4001
      - PG_HOST=postgres
      - PG_USERNAME=postgres
    volumes_from:
      - web
    links:
      - postgres

  postgres:
    image: postgres:9.5 
    ports:
      - "5432"